-- AlterTable
ALTER TABLE "JurnalDebit" ALTER COLUMN "debit" SET DATA TYPE BIGINT,
ALTER COLUMN "keterangan" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "JurnalKredit" ALTER COLUMN "kredit" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "KodeBayar" ALTER COLUMN "nominal" SET DATA TYPE BIGINT,
ALTER COLUMN "nominal_sanksi" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "SPTPD" ALTER COLUMN "omzet" SET DATA TYPE BIGINT,
ALTER COLUMN "pajak" SET DATA TYPE BIGINT;
